services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    api_layer:
        class: ApiBundle\Services\ApiService
        arguments: [ %api.key% ]

